// Code generated by protoc-gen-vkit. DO NOT EDIT.
// versions:
// - protoc-gen-vkit v1.0.0

package handler

import (
	"github.com/visonlv/go-vkit/grpcx"
	
)

func GetList() []interface{} {
	list := make([]interface{}, 0)
	list = append(list, &CategoryService{})
	
	return list
}

func GetApiEndpoint() []*grpcx.ApiEndpoint {
	return []*grpcx.ApiEndpoint{
		{
			Method:"CategoryService.Add",
			Url:"/rpc/config/CategoryService.Add", 
			ClientStream:false, 
			ServerStream:false,
		},{
			Method:"CategoryService.Del",
			Url:"/rpc/config/CategoryService.Del", 
			ClientStream:false, 
			ServerStream:false,
		},{
			Method:"CategoryService.Update",
			Url:"/rpc/config/CategoryService.Update", 
			ClientStream:false, 
			ServerStream:false,
		},{
			Method:"CategoryService.Get",
			Url:"/rpc/config/CategoryService.Get", 
			ClientStream:false, 
			ServerStream:false,
		},{
			Method:"CategoryService.List",
			Url:"/rpc/config/CategoryService.List", 
			ClientStream:false, 
			ServerStream:false,
		},{
			Method:"CategoryService.Page",
			Url:"/rpc/config/CategoryService.Page", 
			ClientStream:false, 
			ServerStream:false,
		},{
			Method:"CategoryService.NodeList",
			Url:"/rpc/config/CategoryService.NodeList", 
			ClientStream:false, 
			ServerStream:false,
		},{
			Method:"CategoryService.HeartBeat",
			Url:"/rpc/config/CategoryService.HeartBeat", 
			ClientStream:true, 
			ServerStream:true,
		},
	}
}
