IsDebug = true

# 服务启动的
[Server]
Address="0.0.0.0"
GrpcPort = 10003

[Mysql]
Uri="root:123456@tcp(10.55.132.187:3306)/engine?charset=utf8mb4&parseTime=True&loc=Local"
MaxConn=100
MaxIdel=10
MaxLifeTime=3600