// Code generated by protoc-gen-vkit. DO NOT EDIT.
// versions:
// - protoc-gen-vkit v1.0.0

package handler

import (
	"github.com/visonlv/go-vkit/grpcx"
	
)

func GetList() []interface{} {
	list := make([]interface{}, 0)
	list = append(list, &DeviceService{})
	list = append(list, &ProductService{})
	list = append(list, &ProductModelService{})
	list = append(list, &RuleService{})
	
	return list
}

func GetApiEndpoint() []*grpcx.ApiEndpoint {
	return []*grpcx.ApiEndpoint{
		{
			Method:"DeviceService.Add",
			Url:"/rpc/thing/DeviceService.Add", 
			ClientStream:false, 
			ServerStream:false,
		},{
			Method:"DeviceService.Del",
			Url:"/rpc/thing/DeviceService.Del", 
			ClientStream:false, 
			ServerStream:false,
		},{
			Method:"DeviceService.Update",
			Url:"/rpc/thing/DeviceService.Update", 
			ClientStream:false, 
			ServerStream:false,
		},{
			Method:"DeviceService.Get",
			Url:"/rpc/thing/DeviceService.Get", 
			ClientStream:false, 
			ServerStream:false,
		},{
			Method:"DeviceService.List",
			Url:"/rpc/thing/DeviceService.List", 
			ClientStream:false, 
			ServerStream:false,
		},{
			Method:"DeviceService.ListGateway",
			Url:"/rpc/thing/DeviceService.ListGateway", 
			ClientStream:false, 
			ServerStream:false,
		},{
			Method:"DeviceService.Page",
			Url:"/rpc/thing/DeviceService.Page", 
			ClientStream:false, 
			ServerStream:false,
		},{
			Method:"DeviceService.Auth",
			Url:"/rpc/thing/DeviceService.Auth", 
			ClientStream:false, 
			ServerStream:false,
		},{
			Method:"DeviceService.Properties",
			Url:"/rpc/thing/DeviceService.Properties", 
			ClientStream:false, 
			ServerStream:false,
		},{
			Method:"ProductService.Add",
			Url:"/rpc/thing/ProductService.Add", 
			ClientStream:false, 
			ServerStream:false,
		},{
			Method:"ProductService.Del",
			Url:"/rpc/thing/ProductService.Del", 
			ClientStream:false, 
			ServerStream:false,
		},{
			Method:"ProductService.Update",
			Url:"/rpc/thing/ProductService.Update", 
			ClientStream:false, 
			ServerStream:false,
		},{
			Method:"ProductService.Get",
			Url:"/rpc/thing/ProductService.Get", 
			ClientStream:false, 
			ServerStream:false,
		},{
			Method:"ProductService.List",
			Url:"/rpc/thing/ProductService.List", 
			ClientStream:false, 
			ServerStream:false,
		},{
			Method:"ProductService.Page",
			Url:"/rpc/thing/ProductService.Page", 
			ClientStream:false, 
			ServerStream:false,
		},{
			Method:"ProductService.GetModel",
			Url:"/rpc/thing/ProductService.GetModel", 
			ClientStream:false, 
			ServerStream:false,
		},{
			Method:"ProductService.UpdateModel",
			Url:"/rpc/thing/ProductService.UpdateModel", 
			ClientStream:false, 
			ServerStream:false,
		},{
			Method:"ProductModelService.Add",
			Url:"/rpc/thing/ProductModelService.Add", 
			ClientStream:false, 
			ServerStream:false,
		},{
			Method:"ProductModelService.Del",
			Url:"/rpc/thing/ProductModelService.Del", 
			ClientStream:false, 
			ServerStream:false,
		},{
			Method:"ProductModelService.Update",
			Url:"/rpc/thing/ProductModelService.Update", 
			ClientStream:false, 
			ServerStream:false,
		},{
			Method:"ProductModelService.Get",
			Url:"/rpc/thing/ProductModelService.Get", 
			ClientStream:false, 
			ServerStream:false,
		},{
			Method:"ProductModelService.List",
			Url:"/rpc/thing/ProductModelService.List", 
			ClientStream:false, 
			ServerStream:false,
		},{
			Method:"ProductModelService.Page",
			Url:"/rpc/thing/ProductModelService.Page", 
			ClientStream:false, 
			ServerStream:false,
		},{
			Method:"RuleService.Add",
			Url:"/rpc/thing/RuleService.Add", 
			ClientStream:false, 
			ServerStream:false,
		},{
			Method:"RuleService.Del",
			Url:"/rpc/thing/RuleService.Del", 
			ClientStream:false, 
			ServerStream:false,
		},{
			Method:"RuleService.Update",
			Url:"/rpc/thing/RuleService.Update", 
			ClientStream:false, 
			ServerStream:false,
		},{
			Method:"RuleService.Get",
			Url:"/rpc/thing/RuleService.Get", 
			ClientStream:false, 
			ServerStream:false,
		},{
			Method:"RuleService.List",
			Url:"/rpc/thing/RuleService.List", 
			ClientStream:false, 
			ServerStream:false,
		},{
			Method:"RuleService.Page",
			Url:"/rpc/thing/RuleService.Page", 
			ClientStream:false, 
			ServerStream:false,
		},
	}
}
