// Code generated by protoc-gen-vkit.
// versions:
// - protoc-gen-vkit v1.0.0

package handler

import (
	context "context"

	pb "github.com/visonlv/iot-engine/notify/proto"
)

type NotifyConfigService struct {
}

func (the *NotifyConfigService) Add(ctx context.Context, req *pb.NotifyConfigAddReq, resp *pb.NotifyConfigAddResp) error {
	return nil
}

func (the *NotifyConfigService) Del(ctx context.Context, req *pb.NotifyConfigDelReq, resp *pb.NotifyConfigDelResp) error {
	return nil
}

func (the *NotifyConfigService) Update(ctx context.Context, req *pb.NotifyConfigUpdateReq, resp *pb.NotifyConfigUpdateResp) error {
	return nil
}

func (the *NotifyConfigService) Get(ctx context.Context, req *pb.NotifyConfigGetReq, resp *pb.NotifyConfigGetResp) error {
	return nil
}

func (the *NotifyConfigService) List(ctx context.Context, req *pb.NotifyConfigListReq, resp *pb.NotifyConfigListResp) error {
	return nil
}

func (the *NotifyConfigService) Page(ctx context.Context, req *pb.NotifyConfigPageReq, resp *pb.NotifyConfigPageResp) error {
	return nil
}
